// Generated by delombok at Wed Oct 02 19:12:43 GMT 2019 (rank 819) copied from https://github.com/mplushnikov/lombok-intellij-plugin/blob/ff0ac206568b3fd2ee238a0b6efed7ae01a3f8bf/testData/after/TolerateTest.java

import java.util.regex.Pattern;

class Tolerate {
	private Pattern pattern;

	public void setPattern(String pattern) {
		setPattern(Pattern.compile(pattern));
	}

	@java.lang.SuppressWarnings("all")
	public void setPattern(final Pattern pattern) {
		this.pattern = pattern;
	}

	@java.lang.SuppressWarnings("all")
	public Pattern getPattern() {
		return this.pattern;
	}
}

class Tolerate2 {
	private final Pattern pattern;

	public Tolerate2 withPattern(String pattern) {
		return withPattern(Pattern.compile(pattern));
	}

	public Tolerate2 withPattern(String nameGlob, String extensionGlob) {
		return withPattern(nameGlob.replace("*", ".*") + "\\." + extensionGlob.replace("*", ".*"));
	}

	@java.lang.SuppressWarnings("all")
	public Pattern getPattern() {
		return this.pattern;
	}

	@java.lang.SuppressWarnings("all")
	public Tolerate2 withPattern(final Pattern pattern) {
		return this.pattern == pattern ? this : new Tolerate2(pattern);
	}

	@java.lang.SuppressWarnings("all")
	public Tolerate2(final Pattern pattern) {
		this.pattern = pattern;
	}
}
